let age = 13;
let score = 80;
let lectures = 5;
let days = 7;
let weeks = 12;
let IslogIn = 1;
let name1 = "678bn";
let name2 = "abc";
let state = null;
let city;
let country = "";
let ans = true;
let ageInString = String(age);
let scoreInString = String(score);
let lecturesInString = String(lectures);
let daysInString = String(days);
let weeksInString = String(weeks);
let booleanlogIn = Boolean(IslogIn);
let newname1 = Number(name1);
console.log(newname1);
console.log(age);
console.log(ageInString);
console.log(scoreInString);
console.log(lecturesInString);
console.log(daysInString);
console.log(weeksInString);
console.log(booleanlogIn);
console.log(typeof name2);
console.log(typeof ageInString);
console.log(typeof state);
console.log(typeof city);
console.log(typeof country);
console.log(typeof ans);
console.log(typeof name1);
console.log(name1);